# This file is derived from the example BIRD configuration at
# https://gitlab.nic.cz/labs/bird/-/blob/3b522a1e5cd034196cd0f5c0eab4d9e87f0f2a8a/doc/bird.conf.example .

# Configure logging
log syslog all;

# Set router ID. It is a unique identification of your router, usually one of
# IPv4 addresses of the router.
router id 10.0.0.2;

# The Device protocol is not a real routing protocol. It does not generate any
# routes and it only serves as a module for getting information about network
# interfaces from the kernel. It is necessary in almost any configuration.
protocol device {
}

# The direct protocol is not a real routing protocol. It automatically generates
# direct routes to all network interfaces. Can exist in as many instances as you
# wish if you want to populate multiple routing tables with direct routes.
protocol direct {
	disabled;		# Disable by default
	ipv4;			# Connect to default IPv4 table
	ipv6;			# ... and to default IPv6 table
}

# The Kernel protocol is not a real routing protocol. Instead of communicating
# with other routers in the network, it performs synchronization of BIRD
# routing tables with the OS kernel. One instance per table.
protocol kernel {
	ipv4 {			# Connect protocol to IPv4 table by channel
	      export all;	# Export to protocol. default is export none
	};
}

# Another instance for IPv6, skipping default options
protocol kernel {
	ipv6 { export all; };
}

# OSPF example, both OSPFv2 and OSPFv3 are supported
protocol ospf {
	ipv4 {
		import all;
		export where source = RTS_STATIC;
	};
	area 0 {
		interface "veth_right" {
			type broadcast;		# Detected by default
			cost 10;		# Interface metric
			hello 3;		# Default hello period 10 is too long
			dead 17;
		};
		interface "lo" {
			stub;			# Stub interface, just propagate it
		};
	};
}
